### ISSUE TITLE
Backup file format documentation should state that space after bytes-length is optional

### ISSUE THREAD

**Issue by aniketbhatnagar** [aerospike/aerospike-tools-backup#6]
it looks like space after bytes-length in bin data in records section (["-"] [SP] ["B"] ["!"]? [SP] [escape({bin-name})] [SP] [{bytes-length}] [SP] [{bytes-data}] [LF]) is optional if bytes-length is 0. This should be documented in format. 

Is this the case with record header (["+"] [SP] ["k"] [SP] ["B"] ["!"]? [SP] [{bytes-length}] [SP] [{bytes-data}] [LF]) as well?

**Comment by uncle-betty** [comment]
Thanks for reporting this. Interesting. The space character shouldn't be optional. Can you provide a sample backup file with the missing space character, which is properly restored?

I just manually created a backup file with a missing space character and `asrestore` reports an error:

`Invalid character \x0a in backup block (line 10, col 8), expected digit`

When parsing the length field, `asrestore` expects to find digits until it hits said space character. Instead, with the space character missing, the line ends right after the length field and `asrestore` finds an LF character (0x0a) instead of a space character. Hence the error message.

**Comment by aniketbhatnagar** [comment]
Apologies for the false alarm. You are right, the backup does have a space even if length is 0. My IDE incorrectly formatted the file.

**Comment by uncle-betty** [comment]
Thanks for following up! Please let us know, if there's anything else that we can do.
